### ISSUE TITLE
When using in 2018.1 or newer, a compile error occurs in ImporterPropertiesModule

### ISSUE THREAD

**Issue by mdawsonuk** [Unity-Technologies/asset-auditing-tools#3]
In this block of code
```
#if UNITY_2018_1_OR_NEWER
// TODO on 2018 allow for the use of a Preset instead of an Object reference
public Preset m_Preset;
#endif
```
the Preset type is not qualified in the using declarations. Adding a reference to UnityEditor.Presets will fix it.

**Comment by AndyMUnity** [comment]
Thank you Stormy, I did not realise this was being used by anyone and no testing has been done for 2018+, the intended minimum version will be 2017. Pushed a fix to this, and will do a test pass on all versions :)

**Comment by mdawsonuk** [comment]
We're not using it per-se, as it is very obviously still in development - unfortunately when we imported it into a brand new project it didn't seem usable. However, we're certainly interested in it as allows for consistent settings across the entire project :) Keep it up!
