### ISSUE TITLE
In 2019.1, the editor for a Asset Auditor profile does not work

### ISSUE THREAD

**Issue by mdawsonuk** [Unity-Technologies/asset-auditing-tools#4]
In 2018.4, the asset auditor's editor works as expected. However, in 2019.1, it appears that the UI doesn't function as expected, displaying only the Lock to Folder toggle instead of the other content.

**Comment by AndyMUnity** [comment]
Thank you Stormy, I have made a Bug report with Unity Editor (1169234) and added a workaround for 2019 until that is resolved.
